name: 'stock-blog-with-sns'
description: '종목 AI 리포트를 기반으로 블로그 포스트와 SNS용 짧은 문구까지 자동 생성하는 오케스트라 워크플로우입니다.'
author: 'young'

# Paths
installed_path: '{project-root}/.bmad/custom/workflows/stock-blog-with-sns'
template: '{installed_path}/template.md'
instructions: '{installed_path}/instructions.md'
validation: '{installed_path}/checklist.md'

# Critical variables from config
config_source: '{project-root}/.bmad/bmb/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
date: system-generated

# Output
default_output_file: '{output_folder}/blog-posts/{{date}}/{{stock_code}}-{{stock_name}}-with-sns.md'

# Invocation control
standalone: true

# Workflow dependencies
blog_post_generator_workflow: '{project-root}/.bmad/custom/workflows/blog-post-generator/workflow.yaml'

# Input parameters (사용자가 제공)
stock_code: ''           # 예: "005930"
stock_name: ''           # 예: "삼성전자"

# SNS 플랫폼 설정
sns_platforms:
  - name: "Twitter/X"
    char_limit: 280
  - name: "Instagram"
    char_limit: 2200
  - name: "LinkedIn"
    char_limit: 3000

# 이미지 프롬프트 생성 설정
image_prompts:
  enabled: true
  min_count: 3
  max_count: 6
  styles:
    - "인포그래픽/다이어그램"
    - "일러스트/캐릭터"
    - "뉴스 스타일"
    - "숫자 강조"
  preferred_tool: "Ideogram"  # 한글 지원 최적

# 톤&매너 설정 (blog-post-generator에서 상속)
writing_style:
  tone: "혼합형"  # 정보=존댓말, 감정=반말
  avoid:
    - "마침표 과다"
    - "불릿 포인트 나열"
    - "이모지 과다"
  use:
    - "구어체 종결어미: ~거든요, ~거예요, ~지, ~더라고요"
    - "지시어: 이거, 그거, 저거"
    - "접속사: 근데, 그래서, 솔직히"
    - "짧은 문장"
    - "솔직한 감정 표현"
