name: 'blog-post-generator'
description: '주식 분석 AI 리포트를 블로그 포스트로 자동 생성 (화면 캡처 + 자연스러운 글쓰기)'

# Paths
installed_path: '{project-root}/.bmad/custom/workflows/blog-post-generator'
template: '{installed_path}/template.md'
instructions: '{installed_path}/instructions.md'
validation: '{installed_path}/checklist.md'

# Critical variables from config
config_source: '{project-root}/.bmad/bmb/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
date: system-generated

# Output
default_output_file: '{output_folder}/blog-posts/{{date}}/{{stock_code}}-{{stock_name}}.md'

# Invocation control
standalone: true

# Workflow-specific variables
azak_base_url: 'https://azak.ngrok.app/preview'
azak_token: '09d1cddeaf2e87bb61cf7a1f98bba17ad941f3e5eb9ef40f83719a97b332ef19'

# Preview paths
azak_dashboard_path: '/dashboard'
azak_stocks_list_path: '/stocks'
azak_stock_detail_path: '/stocks/{{stock_code}}'

# Input parameters (사용자가 제공)
stock_code: ''              # 예: "005930"
stock_name: ''              # 예: "삼성전자"
category: '종목 분석'       # 기본값: 종목 분석

# Playwright MCP settings
screenshot_output: '{output_folder}/blog-posts/{{date}}'

# A/B 모델 정보
model_a_name: ''           # 예: "Qwen3 Max"
model_b_name: ''           # 예: "DeepSeek V3.2"

# 톤&매너 설정
writing_style:
  tone: "혼합형"  # 정보=존댓말, 감정=반말
  avoid:
    - "마침표 과다"
    - "불릿 포인트 나열"
    - "이모지 과다 (섹션당 0~1개)"
    - "여러분, ~하세요 클리셰"
  use:
    - "구어체 종결어미: ~거든, ~거야, ~지, ~더라"
    - "지시어: 이거, 그거, 저거"
    - "접속사: 근데, 그래서, 솔직히"
    - "짧은 문장"
    - "솔직한 감정 표현"

# 블로그 컨셉
blog_concept: "성장형 블로거 (주린이가 같이 배우는 컨셉)"
blogger_persona: "주식 시작한지 3개월, AI 도구 만들어가며 공부 중"

# 필수 CTA
cta_coffee_required: true
cta_premium_optional: true
disclaimer_required: true
model_transparency_required: true
